name: make-modpack

on:
  push:
    branches:
      - mainline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@mainline
        with:
          fetch-depth: 1
      - name: generate config
        run: 'echo "twitch_token: ${{ secrets.CURSE_TOKEN }}" > config.yml'
      - name: build client thing
        run: make github_client
      - name: build server thing
        run: make github_server
      - name: upload artifact modpack i guess
        uses: actions/upload-artifact@v2
        with:
          name: ttmb-0.0.1
          path: artifacts/github/client
      - name: upload server modpack i guess
        uses: actions/upload-artifact@v2
        with:
          name: ttmb-server-0.0.1
          path: artifacts/github/server
