name: make-modpack

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: generate config
        run: 'echo "twitch_token: ${{ secrets.CURSE_TOKEN }}" > config.yml'
      - name: build thing
        run: make build
      - name: upload artifact modpack i guess
        uses: actions/upload-artifact@v2
        with:
          name: ttmb-0.0.1
          path: build/release/ttmb-0.0.1.zip
